### ISSUE TITLE
CR/LF at each @ symbol in Field Annotation

### ISSUE THREAD

**Issue by jasonlones** [smartinkc/Multilingual#20]
The Multilingual module is placing a carriage return and/or line feed in the Field Annotation box for each iteration of the '@' symbol (i.e. action tag) in the data dictionary.  This is causing issues when downloading and opening the data dictionary from REDCap.

**Comment by smartinkc** [comment]
Hi Jason, we are going to replace the carriage return with spaces in the next version.

**Comment by smartinkc** [comment]
Jason, I submitted a new version, 1.9.0 that replaces the carriage return in the action tag with spaces.  It only does this when you save a field in the online designer.  But maybe you'd have a chance to test this and see if it's working?  You could download the data dictionary and open it in notepad++ or something similar.  Then replace all \n@ with a space and then try to upload it.  Also, if you're using html in any fields, make sure to use a single quote instead of a double quote to wrap any styles or classes.  This should allow you to download a data dictionary, modify it and upload it.  Please let me know if this works for you when the new version is out there.
